In [ ]:
import pandas as pd

# Option A: if you published to web, paste that CSV URL here
df = pd.read_csv('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv')

# Option B: if you uploaded the file manually instead, use this line instead:
# df = pd.read_csv('your_filename.csv')

df.head(10)

,UPI Remitter Members - Top 50 Members (Jan'26),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
1,1,State Bank of India,"5,855.79",92.07%,7.61%,0.32%,23.23,95.90%
2,2,HDFC Bank Ltd.,"1,651.17",94.08%,5.87%,0.05%,4.63,92.59%
3,3,Bank of Baroda,"1,542.14",89.46%,10.53%,0.01%,7.00,99.53%
4,4,Union Bank of India,"1,353.05",91.03%,8.72%,0.24%,5.87,82.26%
5,5,Punjab National Bank,"1,222.89",88.58%,10.88%,0.54%,8.57,79.78%
6,6,Canara Bank,"1,093.77",90.83%,8.63%,0.55%,4.96,82.46%
7,7,Kotak Mahindra Bank,"1,091.42",90.27%,9.73%,0.00%,3.90,98.25%
8,8,Axis Bank Ltd.,"1,016.49",94.22%,5.78%,0.00%,2.73,97.00%
9,9,INDIA POST PAYMENTS BANK LIMITED,832.71,82.08%,17.28%,0.64%,6.51,94.82%

In [ ]:
import pandas as pd

# header=1 tells pandas: skip row 0 (the title), use row 1 as column names
df = pd.read_csv('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv', header=1)

df.head(10)

,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
0,1,State Bank of India,"5,855.79",92.07%,7.61%,0.32%,23.23,95.90%
1,2,HDFC Bank Ltd.,"1,651.17",94.08%,5.87%,0.05%,4.63,92.59%
2,3,Bank of Baroda,"1,542.14",89.46%,10.53%,0.01%,7.00,99.53%
3,4,Union Bank of India,"1,353.05",91.03%,8.72%,0.24%,5.87,82.26%
4,5,Punjab National Bank,"1,222.89",88.58%,10.88%,0.54%,8.57,79.78%
5,6,Canara Bank,"1,093.77",90.83%,8.63%,0.55%,4.96,82.46%
6,7,Kotak Mahindra Bank,"1,091.42",90.27%,9.73%,0.00%,3.90,98.25%
7,8,Axis Bank Ltd.,"1,016.49",94.22%,5.78%,0.00%,2.73,97.00%
8,9,INDIA POST PAYMENTS BANK LIMITED,832.71,82.08%,17.28%,0.64%,6.51,94.82%
9,10,ICICI Bank Ltd.,764.26,95.29%,4.30%,0.40%,2.11,81.55%

In [ ]:
# Keep only the 5 banks we locked in
target_banks = [
    'State Bank of India',
    'Bank of Baroda',
    'HDFC Bank Ltd.',
    'Union Bank of India',
    'Punjab National Bank'
]

df_filtered = df[df['UPI Remitter Banks'].isin(target_banks)].copy()

# Check we actually got all 5 — if this prints fewer than 5 rows, a bank name doesn't match exactly
print(df_filtered.shape)
df_filtered

(5, 8)

,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
0,1,State Bank of India,"5,855.79",92.07%,7.61%,0.32%,23.23,95.90%
1,2,HDFC Bank Ltd.,"1,651.17",94.08%,5.87%,0.05%,4.63,92.59%
2,3,Bank of Baroda,"1,542.14",89.46%,10.53%,0.01%,7.00,99.53%
3,4,Union Bank of India,"1,353.05",91.03%,8.72%,0.24%,5.87,82.26%
4,5,Punjab National Bank,"1,222.89",88.58%,10.88%,0.54%,8.57,79.78%

In [ ]:
# Keep just what we need
df_clean = df_filtered[['UPI Remitter Banks', 'Total Volume (In Mn)', 'TD%']].copy()

# Rename to simpler, code-friendly column names
df_clean.columns = ['bank', 'total_volume_mn', 'td_pct']

# TD% currently looks like "0.32%" (a string) — strip the % sign and convert to float
df_clean['td_pct'] = df_clean['td_pct'].astype(str).str.replace('%', '').astype(float)

# Tag this slice with its month
df_clean['month'] = '2026-01'

df_clean

                   bank total_volume_mn  td_pct    month
0   State Bank of India        5,855.79    0.32  2026-01
1        HDFC Bank Ltd.        1,651.17    0.05  2026-01
2        Bank of Baroda        1,542.14    0.01  2026-01
3   Union Bank of India        1,353.05    0.24  2026-01
4  Punjab National Bank        1,222.89    0.54  2026-01

In [ ]:
# Save this month's clean slice
df_clean.to_csv('upi_td_2026_01.csv', index=False)
print("Saved:", df_clean.shape)

Saved: (5, 4)

In [ ]:
def clean_upi_month(filepath, header_row, month_label, target_banks):
    """
    Reads a raw NPCI 'Top 50 Member Performance' CSV export,
    filters to target banks, cleans TD%, tags with month.
    """
    raw = pd.read_csv(filepath, header=header_row)
    filtered = raw[raw['UPI Remitter Banks'].isin(target_banks)].copy()

    if filtered.shape[0] != len(target_banks):
        print(f"⚠️ WARNING: expected {len(target_banks)} banks, got {filtered.shape[0]} for {month_label}")
        print("Unique bank names in this file:", raw['UPI Remitter Banks'].unique())

    clean = filtered[['UPI Remitter Banks', 'Total Volume (In Mn)', 'TD%']].copy()
    clean.columns = ['bank', 'total_volume_mn', 'td_pct']
    clean['td_pct'] = clean['td_pct'].astype(str).str.replace('%', '').astype(float)
    clean['month'] = month_label

    return clean

target_banks = [
    'State Bank of India',
    'Bank of Baroda',
    'HDFC Bank Ltd.',
    'Union Bank of India',
    'Punjab National Bank'
]

# Test it on the same Jan 2026 file to confirm the function works identically to our manual steps
test = clean_upi_month('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv', header_row=1, month_label='2026-01', target_banks=target_banks)
test

                   bank total_volume_mn  td_pct    month
0   State Bank of India        5,855.79    0.32  2026-01
1        HDFC Bank Ltd.        1,651.17    0.05  2026-01
2        Bank of Baroda        1,542.14    0.01  2026-01
3   Union Bank of India        1,353.05    0.24  2026-01
4  Punjab National Bank        1,222.89    0.54  2026-01

In [ ]:
test = clean_upi_month('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv', header_row=1, month_label='2026-01', target_banks=target_banks)
test

                   bank total_volume_mn  td_pct    month
0   State Bank of India        5,855.79    0.32  2026-01
1        HDFC Bank Ltd.        1,651.17    0.05  2026-01
2        Bank of Baroda        1,542.14    0.01  2026-01
3   Union Bank of India        1,353.05    0.24  2026-01
4  Punjab National Bank        1,222.89    0.54  2026-01

In [ ]:
test = clean_upi_month(
    '/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv',
    header_row=1,
    month_label='2026-01',
    target_banks=target_banks
)
test

                   bank total_volume_mn  td_pct    month
0   State Bank of India        5,855.79    0.32  2026-01
1        HDFC Bank Ltd.        1,651.17    0.05  2026-01
2        Bank of Baroda        1,542.14    0.01  2026-01
3   Union Bank of India        1,353.05    0.24  2026-01
4  Punjab National Bank        1,222.89    0.54  2026-01

In [ ]:
import os

csv_files = [f for f in os.listdir('/content') if f.endswith('.csv')]
csv_files.sort()
for f in csv_files:
    print(f)

Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
UPI_Master_Dataset.csv
iss_monthly (1).csv
iss_monthly.csv
upi_td_2026_01.csv

In [ ]:
import os

csv_files = [f for f in os.listdir('/content') if f.endswith('.csv')]
csv_files.sort()
print(len(csv_files), "files found:")
for f in csv_files:
    print(f)

5 files found:
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
UPI_Master_Dataset.csv
iss_monthly (1).csv
iss_monthly.csv
upi_td_2026_01.csv

In [ ]:
import os

csv_files = [f for f in os.listdir('/content') if f.endswith('.csv')]
print(len(csv_files), "files found:\n")
for f in sorted(csv_files):
    print(f)

5 files found:

Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
UPI_Master_Dataset.csv
iss_monthly (1).csv
iss_monthly.csv
upi_td_2026_01.csv

In [ ]:
import os

all_files = os.listdir('/content')
print(len(all_files), "total items found:\n")
for f in sorted(all_files):
    print(repr(f))

36 total items found:

'.config'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv'
'Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx'
'UPI_Master_Dataset.csv'
'drive'
'iss_monthly (1).csv'
'iss_monthly.csv'
'sample_data'
'upi_td_2026_01.csv'

In [ ]:
import pandas as pd

def clean_upi_month(filepath, header_row, month_label, target_banks):
    raw = pd.read_excel(filepath, header=header_row)  # changed from read_csv to read_excel
    filtered = raw[raw['UPI Remitter Banks'].isin(target_banks)].copy()

    if filtered.shape[0] != len(target_banks):
        print(f"⚠️ WARNING: expected {len(target_banks)} banks, got {filtered.shape[0]} for {month_label}")
        print("Unique bank names in this file:", raw['UPI Remitter Banks'].unique())

    clean = filtered[['UPI Remitter Banks', 'Total Volume (In Mn)', 'TD%']].copy()
    clean.columns = ['bank', 'total_volume_mn', 'td_pct']
    clean['td_pct'] = clean['td_pct'].astype(str).str.replace('%', '').astype(float)
    clean['month'] = month_label

    return clean

In [ ]:
raw_check = pd.read_excel('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx', header=None)
raw_check.head(8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Jan'25),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank of India,4664.49,0.9122,0.0793,0.0084,15.63,0.9706
3,2,HDFC Bank Ltd.,1419.33,0.9364,0.0628,0.0008,4.12,0.9891
4,3,Bank of Baroda,1159.99,0.9122,0.085,0.0028,3.31,0.9733
5,4,Union Bank of India,1086.26,0.9125,0.0807,0.0068,5.11,0.5675
6,5,Punjab National Bank,976.62,0.8956,0.1031,0.0013,2.99,0.9861
7,6,Kotak Mahindra Bank,889.41,0.8973,0.1022,0.0006,2.24,0.8954

In [ ]:
import pandas as pd

def find_header_row(filepath):
    """Scan the first few rows to find which one has 'UPI Remitter Banks'."""
    if filepath.endswith('.csv'):
        probe = pd.read_csv(filepath, header=None, nrows=5)
    else:
        probe = pd.read_excel(filepath, header=None, nrows=5)
    for i in range(len(probe)):
        if probe.iloc[i].astype(str).str.contains('UPI Remitter Banks').any():
            return i
    raise ValueError(f"Could not find header row in {filepath}")

def parse_td(val):
    """Handle both '0.32%' text and 0.0084 fraction formats."""
    if isinstance(val, str):
        return float(val.replace('%', ''))
    else:
        return float(val) * 100  # fraction -> percent

def clean_upi_month(filepath, month_label, target_banks):
    header_row = find_header_row(filepath)
    if filepath.endswith('.csv'):
        raw = pd.read_csv(filepath, header=header_row)
    else:
        raw = pd.read_excel(filepath, header=header_row)

    filtered = raw[raw['UPI Remitter Banks'].isin(target_banks)].copy()
    if filtered.shape[0] != len(target_banks):
        print(f"⚠️ WARNING: expected {len(target_banks)} banks, got {filtered.shape[0]} for {month_label}")
        print("Unique bank names found:", raw['UPI Remitter Banks'].unique())

    clean = filtered[['UPI Remitter Banks', 'Total Volume (In Mn)', 'TD%']].copy()
    clean.columns = ['bank', 'total_volume_mn', 'td_pct']
    clean['td_pct'] = clean['td_pct'].apply(parse_td)
    clean['month'] = month_label
    return clean

In [ ]:
raw_check = pd.read_excel('/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx', header=None)
raw_check.head(8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Mar'25),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr_No,upi_remitter_banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank of India,4956.07,0.9201,0.0709,0.009,20.26,0.863
3,2,HDFC Bank Ltd.,1513.14,0.9398,0.06,0.0002,4.92,0.9721
4,3,Bank of Baroda,1270.6,0.8947,0.105,0.0003,3.86,0.9532
5,4,Union Bank of India,1173.28,0.9158,0.0836,0.0006,3.51,0.8997
6,5,Punjab National Bank,1043.06,0.9022,0.0945,0.0033,3.83,0.913
7,6,Kotak Mahindra Bank,938.6,0.8978,0.1019,0.0002,2.42,0.0094

In [ ]:
import os

# Folder where your uploaded files are stored
folder_path = "/content"

# List all Excel and CSV files
files = sorted([
    f for f in os.listdir(folder_path)
    if f.endswith(".xlsx") or f.endswith(".csv")
])

print("Number of files found:", len(files))
print()

for file in files:
    print(file)

Number of files found: 33

Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
UPI_Master_Dataset.csv
iss_monthly (1).csv
iss_monthly.csv
upi_td_2026_01.csv

In [ ]:
import os

files = sorted(os.listdir("/content"))

for file in files:
    print(file)

.config
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
UPI_Master_Dataset.csv
drive
iss_monthly (1).csv
iss_monthly.csv
sample_data
upi_td_2026_01.csv

In [ ]:
import pandas as pd

sample_file = "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx"

raw = pd.read_excel(
    sample_file,
    header=None,
    dtype=str
)

print("Shape:", raw.shape)

display(raw.head(20))

Shape: (52, 8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Jan'25),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank of India,4664.49,0.9122,0.0793,0.0084,15.63,0.9706
3,2,HDFC Bank Ltd.,1419.33,0.9364,0.0628,0.0008,4.12,0.9891
4,3,Bank of Baroda,1159.99,0.9122,0.085,0.0028,3.31,0.9733
5,4,Union Bank of India,1086.26,0.9125,0.0807,0.0068,5.11,0.5675
6,5,Punjab National Bank,976.62,0.8956,0.1031,0.0013,2.99,0.9861
7,6,Kotak Mahindra Bank,889.41,0.8973,0.1022,0.0006,2.24,0.8954
8,7,Canara Bank,835.68,0.9183,0.078,0.0037,3.08,0.7991
9,8,Axis Bank Ltd.,821.68,0.9347,0.0651,0.0002,1.83,0.9514
10,9,ICICI Bank Ltd.,692.71,0.9498,0.0496,0.0006,1.36,0.9836
11,10,Bank Of India,556.22,0.9258,0.0705,0.0037,2.28,0.7253
12,11,Airtel Payments Bank Limited,553.22,0.8584,0.1372,0.0045,2.47,0.9368
13,12,Indian Bank,539.83,0.919,0.0804,0.0006,1.33,0.9395
14,13,India Post Payments Bank Ltd.,496.43,0.8369,0.148,0.0151,2.6,0.5791
15,14,Indian Overseas Bank,264.2,0.9214,0.0755,0.0031,0.74,0.97
16,15,Federal Bank Ltd.,250.01,0.9129,0.0847,0.0024,0.5,0.9971
17,16,Central Bank of India,246.28,0.8569,0.1346,0.0085,1.18,0.7551
18,17,UCO Bank,231.83,0.9085,0.0899,0.0016,0.8,0.8997
19,18,Bank of Maharashtra,194.89,0.923,0.0761,0.0009,0.56,0.8999

In [ ]:
march_file = "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx"

raw = pd.read_excel(
    march_file,
    header=None,
    dtype=str
)

print(raw.shape)

display(raw.head(20))

(52, 8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Mar'25),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr_No,upi_remitter_banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank of India,4956.07,0.9201,0.0709,0.009,20.26,0.863
3,2,HDFC Bank Ltd.,1513.14,0.9398,0.06,0.0002,4.92,0.9721
4,3,Bank of Baroda,1270.6,0.8947,0.105,0.0003,3.86,0.9532
5,4,Union Bank of India,1173.28,0.9158,0.0836,0.0006,3.51,0.8997
6,5,Punjab National Bank,1043.06,0.9022,0.0945,0.0033,3.83,0.913
7,6,Kotak Mahindra Bank,938.6,0.8978,0.1019,0.0002,2.42,0.0094
8,7,Canara Bank,901.11,0.9183,0.0804,0.0013,2.7,0.8781
9,8,Axis Bank Ltd.,883.53,0.9352,0.0645,0.0003,2.25,0.8445
10,9,ICICI Bank Ltd.,730.29,0.9515,0.0472,0.0013,1.83,0.9105
11,10,Bank Of India,595.31,0.9234,0.0708,0.0058,2.67,0.7307
12,11,Indian Bank,589.5,0.9156,0.0821,0.0023,1.97,0.7566
13,12,India Post Payments Bank Limited,570.54,0.8613,0.1354,0.0033,2.31,0.8905
14,13,Airtel Payments Bank Limited,569.69,0.8431,0.1538,0.0031,2.52,0.8884
15,14,Indian Overseas Bank,292.32,0.9193,0.0767,0.004,1.06,0.9187
16,15,Central Bank of India,266.98,0.8615,0.1355,0.003,0.94,0.9479
17,16,Federal Bank Ltd.,256.34,0.9149,0.0846,0.0005,0.57,0.9807
18,17,UCO Bank,254.76,0.8986,0.1005,0.0009,0.96,0.8931
19,18,Fino Payments Bank Ltd.,214.85,0.8762,0.1218,0.0021,1.2,0.7233

In [ ]:
def standardize_columns(columns):
    """
    Standardize column names so different NPCI formats
    become consistent.
    """

    cleaned = []

    for col in columns:

        col = str(col)

        col = col.strip()

        col = col.lower()

        col = col.replace(" ", "_")

        cleaned.append(col)

    return cleaned

In [ ]:
jan = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx",
    header=1
)

jan.columns = standardize_columns(jan.columns)

print(jan.columns.tolist())

['sr._no.', 'upi_remitter_banks', 'total_volume_(in_mn)', 'approved_%', 'bd_%', 'td%', 'total_debit_reversal_count_(in_mn)', 'debit_reversal_success_%']

In [ ]:
mar = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx",
    header=1
)

mar.columns = standardize_columns(mar.columns)

print(mar.columns.tolist())

['sr_no', 'upi_remitter_banks', 'total_volume_(in_mn)', 'approved_%', 'bd_%', 'td%', 'total_debit_reversal_count_(in_mn)', 'debit_reversal_success_%']

In [ ]:
import pandas as pd
import os

def standardize_columns(columns):
    """
    Convert column names to a standard format.
    """

    cleaned = []

    for col in columns:

        col = str(col)

        col = col.strip()

        col = col.lower()

        col = col.replace(" ", "_")

        cleaned.append(col)

    return cleaned


def read_monthly_file(file_path):
    """
    Reads one NPCI monthly file and returns
    a clean DataFrame with standardized columns.
    """

    extension = os.path.splitext(file_path)[1].lower()

    # Read raw file without assuming header
    if extension == ".xlsx":
        raw = pd.read_excel(file_path, header=None, dtype=str)

    elif extension == ".csv":
        raw = pd.read_csv(file_path, header=None, dtype=str)

    else:
        raise ValueError("Unsupported file type.")

    # Detect header row
    header_row = None

    for i in range(min(10, len(raw))):

        row_text = " ".join(
            raw.iloc[i]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        if (
            "td" in row_text and
            "approved" in row_text and
            "remitter" in row_text
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(f"Header not found in {file_path}")

    # Read again using detected header
    if extension == ".xlsx":
        df = pd.read_excel(
            file_path,
            header=header_row
        )

    else:
        df = pd.read_csv(
            file_path,
            header=header_row
        )

    # Standardize column names
    df.columns = standardize_columns(df.columns)

    return df

In [ ]:
jan = read_monthly_file(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx"
)

print(jan.head())

   sr._no.    upi_remitter_banks  total_volume_(in_mn)  approved_%    bd_%  \
0        1   State Bank of India               4664.49      0.9122  0.0793
1        2        HDFC Bank Ltd.               1419.33      0.9364  0.0628
2        3        Bank of Baroda               1159.99      0.9122  0.0850
3        4   Union Bank of India               1086.26      0.9125  0.0807
4        5  Punjab National Bank                976.62      0.8956  0.1031

      td% total_debit_reversal_count_(in_mn)  debit_reversal_success_%
0  0.0084                              15.63                    0.9706
1  0.0008                               4.12                    0.9891
2  0.0028                               3.31                    0.9733
3  0.0068                               5.11                    0.5675
4  0.0013                               2.99                    0.9861

In [ ]:
mar = read_monthly_file(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx"
)

print(mar.head())

   sr_no    upi_remitter_banks  total_volume_(in_mn)  approved_%    bd_%  \
0      1   State Bank of India               4956.07      0.9201  0.0709
1      2        HDFC Bank Ltd.               1513.14      0.9398  0.0600
2      3        Bank of Baroda               1270.60      0.8947  0.1050
3      4   Union Bank of India               1173.28      0.9158  0.0836
4      5  Punjab National Bank               1043.06      0.9022  0.0945

      td% total_debit_reversal_count_(in_mn)  debit_reversal_success_%
0  0.0090                              20.26                    0.8630
1  0.0002                               4.92                    0.9721
2  0.0003                               3.86                    0.9532
3  0.0006                               3.51                    0.8997
4  0.0033                               3.83                    0.9130

In [ ]:
TARGET_BANKS = [
    "State Bank of India",
    "Bank of Baroda",
    "HDFC Bank Ltd.",
    "Union Bank of India",
    "Punjab National Bank"
]

In [ ]:
jan_top5 = jan[
    jan["upi_remitter_banks"].isin(TARGET_BANKS)
].copy()

print("Number of selected banks:", len(jan_top5))

display(jan_top5)

Number of selected banks: 5

,sr._no.,upi_remitter_banks,total_volume_(in_mn),approved_%,bd_%,td%,total_debit_reversal_count_(in_mn),debit_reversal_success_%
0,1,State Bank of India,4664.49,0.9122,0.0793,0.0084,15.63,0.9706
1,2,HDFC Bank Ltd.,1419.33,0.9364,0.0628,0.0008,4.12,0.9891
2,3,Bank of Baroda,1159.99,0.9122,0.0850,0.0028,3.31,0.9733
3,4,Union Bank of India,1086.26,0.9125,0.0807,0.0068,5.11,0.5675
4,5,Punjab National Bank,976.62,0.8956,0.1031,0.0013,2.99,0.9861

In [ ]:
import glob
import re
import os

In [ ]:
all_files = []

all_files.extend(
    glob.glob("/content/*Remitter.xlsx")
)

all_files.extend(
    glob.glob("/content/*Remitter*.csv")
)

all_files = sorted(all_files)

print("Files found:", len(all_files))
print()

for f in all_files:
    print(os.path.basename(f))

Files found: 27

Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx

In [ ]:
def extract_month(filename):

    months = {
        "Jan":"01",
        "Feb":"02",
        "Mar":"03",
        "Apr":"04",
        "May":"05",
        "Jun":"06",
        "Jul":"07",
        "Aug":"08",
        "Sep":"09",
        "Oct":"10",
        "Nov":"11",
        "Dec":"12"
    }

    match = re.search(r"(20\d{2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", filename)

    if match:

        year = match.group(1)

        month = months[match.group(2)]

        return f"{year}-{month}"

    return None

In [ ]:
for f in all_files:
    print(os.path.basename(f), " ---> ", extract_month(os.path.basename(f)))

Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx  --->  2024-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx  --->  2024-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx  --->  2024-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx  --->  2024-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx  --->  2024-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx  --->  2024-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx  --->  2024-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx  --->  2024-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx  --->  2024-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx  --->  2024-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx  --->  2024-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx  --->  2024-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx  --->  2025-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx  --->  2025-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx  --->  2025-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx  --->  2025-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx  --->  2025-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx  --->  2025-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx  --->  2025-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx  --->  2025-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx  --->  2025-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx  --->  2025-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx  --->  2025-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx  --->  2025-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx  --->  2026-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv  --->  2026-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx  --->  2026-01

Build one combined dataframe

In [ ]:
jun = read_monthly_file(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx"
)

print(jun.columns.tolist())

['sr._no.', 'upi_remitter_members', 'total_volume_(in_mn)', 'approved_%', 'bd_%', 'td%', 'total_debit_reversal_count_(in_mn)', 'debit_reversal_success_%']

In [ ]:
display(jun.head())

,sr._no.,upi_remitter_members,total_volume_(in_mn),approved_%,bd_%,td%,total_debit_reversal_count_(in_mn),debit_reversal_success_%
0,1,State Bank of India,4917.29,0.9364,0.0582,0.0054,12.9,0.9827
1,2,HDFC Bank Ltd.,1472.04,0.9530,0.0462,0.0008,1.8,0.9945
2,3,Bank of Baroda,1239.11,0.9109,0.0888,0.0003,3.01,0.9854
3,4,Union Bank of India,1144.76,0.9295,0.0694,0.0011,2.71,0.8894
4,5,Punjab National Bank,1053.00,0.9238,0.0759,0.0002,2.67,0.9901

In [ ]:
import pandas as pd
import os
import glob
import re

# -----------------------------
# Target Banks
# -----------------------------
TARGET_BANKS = [
    "State Bank of India",
    "Bank of Baroda",
    "HDFC Bank Ltd.",
    "Union Bank of India",
    "Punjab National Bank"
]

# -----------------------------
# Standardize Column Names
# -----------------------------
def standardize_columns(columns):

    cleaned = []

    for col in columns:
        col = str(col).strip().lower()

        col = col.replace(" ", "_")
        col = col.replace(".", "")
        col = col.replace("%", "pct")
        col = col.replace("(", "")
        col = col.replace(")", "")

        cleaned.append(col)

    return cleaned


# -----------------------------
# Read Monthly File
# -----------------------------
def read_monthly_file(file_path):

    extension = os.path.splitext(file_path)[1].lower()

    if extension == ".xlsx":
        raw = pd.read_excel(file_path, header=None, dtype=str)

    elif extension == ".csv":
        raw = pd.read_csv(file_path, header=None, dtype=str)

    else:
        raise ValueError("Unsupported file type")

    header_row = None

    for i in range(min(10, len(raw))):

        row_text = " ".join(
            raw.iloc[i]
            .fillna("")
            .astype(str)
            .str.lower()
        )

        if (
            "approved" in row_text
            and "td" in row_text
            and ("remitter" in row_text)
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(f"Header not found in {file_path}")

    if extension == ".xlsx":
        df = pd.read_excel(file_path, header=header_row)

    else:
        df = pd.read_csv(file_path, header=header_row)

    df.columns = standardize_columns(df.columns)

    # Make all files use the same schema
    df.rename(columns={
        "upi_remitter_members": "upi_remitter_banks",
        "upi_remitter_member": "upi_remitter_banks",
        "upi_remitter_bank": "upi_remitter_banks",
        "upi_remitterbanks": "upi_remitter_banks",
        "tdpct": "td_pct",
        "td": "td_pct"
    }, inplace=True)

    return df


# -----------------------------
# Extract Month from Filename
# -----------------------------
def extract_month(filename):

    months = {
        "Jan":"01",
        "Feb":"02",
        "Mar":"03",
        "Apr":"04",
        "May":"05",
        "Jun":"06",
        "Jul":"07",
        "Aug":"08",
        "Sep":"09",
        "Oct":"10",
        "Nov":"11",
        "Dec":"12"
    }

    match = re.search(
        r"(20\d{2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)",
        filename
    )

    if match:
        return f"{match.group(1)}-{months[match.group(2)]}"

    return None


# -----------------------------
# Find Files
# -----------------------------
all_files = []

all_files.extend(glob.glob("/content/*Remitter.xlsx"))
all_files.extend(glob.glob("/content/*Remitter*.csv"))

all_files = sorted(all_files)

print(f"Found {len(all_files)} files\n")


# -----------------------------
# Build Master Dataset
# -----------------------------
master_df = pd.DataFrame()

for file in all_files:

    print("Processing:", os.path.basename(file))

    df = read_monthly_file(file)

    df = df[df["upi_remitter_banks"].isin(TARGET_BANKS)].copy()

    df["month"] = extract_month(os.path.basename(file))

    df = df[
        [
            "month",
            "upi_remitter_banks",
            "total_volume_in_mn",
            "td_pct"
        ]
    ]

    master_df = pd.concat(
        [master_df, df],
        ignore_index=True
    )


print("\nProcessing Complete!\n")

print("Master DataFrame Shape:")
print(master_df.shape)

print("\nRows per Month:")
print(master_df.groupby("month").size())

display(master_df.head(15))

Found 27 files

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx

Processing Complete!

Master DataFrame Shape:
(108, 4)

Rows per Month:
month
2024-01     3
2024-02     3
2024-03     3
2024-04     3
2024-05     3
2024-06     4
2024-07     2
2024-08     2
2024-09     3
2024-10     3
2024-11     3
2024-12     5
2025-01     5
2025-02     5
2025-03     5
2025-04     5
2025-05     5
2025-06     5
2025-07     5
2025-08     5
2025-09     5
2025-10     5
2025-11     5
2025-12     5
2026-01    10
2026-04     1
dtype: int64

      month    upi_remitter_banks total_volume_in_mn td_pct
0   2024-04        Bank of Baroda             898.17  1.59%
1   2024-04   Union Bank of India             837.24  1.59%
2   2024-04  Punjab National Bank             741.90  1.11%
3   2024-08        HDFC Bank Ltd.           1,270.59  0.06%
4   2024-08        Bank of Baroda             985.86  0.60%
5   2024-12   State Bank of India           4,540.13  0.48%
6   2024-12        HDFC Bank Ltd.           1,403.46  0.09%
7   2024-12        Bank of Baroda           1,125.93  0.10%
8   2024-12   Union Bank of India           1,070.69  0.13%
9   2024-12  Punjab National Bank             954.15  0.91%
10  2024-02        Bank of Baroda             786.15  1.03%
11  2024-02   Union Bank of India             754.01  1.68%
12  2024-02  Punjab National Bank             628.99  0.25%
13  2024-01        Bank of Baroda             781.72  0.04%
14  2024-01   Union Bank of India             753.66  1.15%

In [ ]:
print(master_df["td_pct"].head(20))

print()

print(master_df["td_pct"].tail(10))

0     1.59%
1     1.59%
2     1.11%
3     0.06%
4     0.60%
5     0.48%
6     0.09%
7     0.10%
8     0.13%
9     0.91%
10    1.03%
11    1.68%
12    0.25%
13    0.04%
14    1.15%
15    0.27%
16    0.00%
17    0.59%
18    0.22%
19    0.33%
Name: td_pct, dtype: object

98     0.32%
99     0.05%
100    0.01%
101    0.24%
102    0.54%
103    0.32%
104    0.05%
105    0.01%
106    0.24%
107    0.54%
Name: td_pct, dtype: object

In [ ]:
def normalize_td(value):
    """
    Convert all TD values to percentage (%).

    Examples:
        0.0084  -> 0.84
        "0.32%" -> 0.32
    """

    if pd.isna(value):
        return None

    value = str(value).strip()

    # Already stored as percentage string
    if value.endswith("%"):
        return float(value.replace("%", ""))

    # Stored as decimal fraction
    value = float(value)

    return value * 100


# Apply normalization
master_df["td_pct"] = master_df["td_pct"].apply(normalize_td)

print("TD column converted successfully!\n")

display(master_df.head(15))

TD column converted successfully!

      month    upi_remitter_banks total_volume_in_mn  td_pct
0   2024-04        Bank of Baroda             898.17    1.59
1   2024-04   Union Bank of India             837.24    1.59
2   2024-04  Punjab National Bank             741.90    1.11
3   2024-08        HDFC Bank Ltd.           1,270.59    0.06
4   2024-08        Bank of Baroda             985.86    0.60
5   2024-12   State Bank of India           4,540.13    0.48
6   2024-12        HDFC Bank Ltd.           1,403.46    0.09
7   2024-12        Bank of Baroda           1,125.93    0.10
8   2024-12   Union Bank of India           1,070.69    0.13
9   2024-12  Punjab National Bank             954.15    0.91
10  2024-02        Bank of Baroda             786.15    1.03
11  2024-02   Union Bank of India             754.01    1.68
12  2024-02  Punjab National Bank             628.99    0.25
13  2024-01        Bank of Baroda             781.72    0.04
14  2024-01   Union Bank of India             753.66    1.15

In [ ]:
print(master_df["td_pct"].describe())

count    108.000000
mean       0.328056
std        0.363440
min        0.000000
25%        0.075000
50%        0.215000
75%        0.472500
max        1.680000
Name: td_pct, dtype: float64

In [ ]:
master_df["month"] = pd.to_datetime(master_df["month"])

master_df = master_df.sort_values(
    ["month", "upi_remitter_banks"]
).reset_index(drop=True)

display(master_df.head(15))

        month    upi_remitter_banks total_volume_in_mn  td_pct
0  2024-01-01        Bank of Baroda             781.72    0.04
1  2024-01-01  Punjab National Bank             618.95    0.27
2  2024-01-01   Union Bank of India             753.66    1.15
3  2024-02-01        Bank of Baroda             786.15    1.03
4  2024-02-01  Punjab National Bank             628.99    0.25
5  2024-02-01   Union Bank of India             754.01    1.68
6  2024-03-01        Bank of Baroda             882.82    0.45
7  2024-03-01  Punjab National Bank             728.08    0.23
8  2024-03-01   Union Bank of India             848.59    1.40
9  2024-04-01        Bank of Baroda             898.17    1.59
10 2024-04-01  Punjab National Bank             741.90    1.11
11 2024-04-01   Union Bank of India             837.24    1.59
12 2024-05-01        Bank of Baroda             930.35    0.95
13 2024-05-01  Punjab National Bank             785.36    0.31
14 2024-05-01   Union Bank of India             876.18    0.24

In [ ]:
master_df.groupby("month").size()

month
2024-01-01     3
2024-02-01     3
2024-03-01     3
2024-04-01     3
2024-05-01     3
2024-06-01     4
2024-07-01     2
2024-08-01     2
2024-09-01     3
2024-10-01     3
2024-11-01     3
2024-12-01     5
2025-01-01     5
2025-02-01     5
2025-03-01     5
2025-04-01     5
2025-05-01     5
2025-06-01     5
2025-07-01     5
2025-08-01     5
2025-09-01     5
2025-10-01     5
2025-11-01     5
2025-12-01     5
2026-01-01    10
2026-04-01     1
dtype: int64

In [ ]:
master_df.groupby("month").size()

month
2024-01-01     3
2024-02-01     3
2024-03-01     3
2024-04-01     3
2024-05-01     3
2024-06-01     4
2024-07-01     2
2024-08-01     2
2024-09-01     3
2024-10-01     3
2024-11-01     3
2024-12-01     5
2025-01-01     5
2025-02-01     5
2025-03-01     5
2025-04-01     5
2025-05-01     5
2025-06-01     5
2025-07-01     5
2025-08-01     5
2025-09-01     5
2025-10-01     5
2025-11-01     5
2025-12-01     5
2026-01-01    10
2026-04-01     1
dtype: int64

In [ ]:
# Calculate historical statistics for each bank
bank_stats = (
    master_df
    .groupby("upi_remitter_banks")["td_pct"]
    .agg(["mean", "std"])
    .reset_index()
)

print("Historical TD% statistics for each bank:")
display(bank_stats)

Historical TD% statistics for each bank:

     upi_remitter_banks      mean       std
0        Bank of Baroda  0.271923  0.390036
1        HDFC Bank Ltd.  0.048333  0.036178
2  Punjab National Bank  0.330000  0.252328
3   State Bank of India  0.506471  0.203898
4   Union Bank of India  0.476522  0.506320

In [ ]:
# Add bank mean and standard deviation to every row
master_df = master_df.merge(
    bank_stats,
    on="upi_remitter_banks",
    how="left"
)

display(master_df.head(10))

,month,upi_remitter_banks,total_volume_in_mn,td_pct,mean,std
0,2024-01-01,Bank of Baroda,781.72,0.04,0.271923,0.390036
1,2024-01-01,Punjab National Bank,618.95,0.27,0.330000,0.252328
2,2024-01-01,Union Bank of India,753.66,1.15,0.476522,0.506320
3,2024-02-01,Bank of Baroda,786.15,1.03,0.271923,0.390036
4,2024-02-01,Punjab National Bank,628.99,0.25,0.330000,0.252328
5,2024-02-01,Union Bank of India,754.01,1.68,0.476522,0.506320
6,2024-03-01,Bank of Baroda,882.82,0.45,0.271923,0.390036
7,2024-03-01,Punjab National Bank,728.08,0.23,0.330000,0.252328
8,2024-03-01,Union Bank of India,848.59,1.40,0.476522,0.506320
9,2024-04-01,Bank of Baroda,898.17,1.59,0.271923,0.390036

In [ ]:
# Calculate z-score for each bank-month
master_df["z_score"] = (
    (master_df["td_pct"] - master_df["mean"]) /
    master_df["std"]
)

display(master_df.head(15))

,month,upi_remitter_banks,total_volume_in_mn,td_pct,mean,std,z_score
0,2024-01-01,Bank of Baroda,781.72,0.04,0.271923,0.390036,-0.594620
1,2024-01-01,Punjab National Bank,618.95,0.27,0.330000,0.252328,-0.237785
2,2024-01-01,Union Bank of India,753.66,1.15,0.476522,0.506320,1.330143
3,2024-02-01,Bank of Baroda,786.15,1.03,0.271923,0.390036,1.943607
4,2024-02-01,Punjab National Bank,628.99,0.25,0.330000,0.252328,-0.317047
5,2024-02-01,Union Bank of India,754.01,1.68,0.476522,0.506320,2.376912
6,2024-03-01,Bank of Baroda,882.82,0.45,0.271923,0.390036,0.456565
7,2024-03-01,Punjab National Bank,728.08,0.23,0.330000,0.252328,-0.396309
8,2024-03-01,Union Bank of India,848.59,1.40,0.476522,0.506320,1.823902
9,2024-04-01,Bank of Baroda,898.17,1.59,0.271923,0.390036,3.379372
10,2024-04-01,Punjab National Bank,741.90,1.11,0.330000,0.252328,3.091211
11,2024-04-01,Union Bank of India,837.24,1.59,0.476522,0.506320,2.199159
12,2024-05-01,Bank of Baroda,930.35,0.95,0.271923,0.390036,1.738498
13,2024-05-01,Punjab National Bank,785.36,0.31,0.330000,0.252328,-0.079262
14,2024-05-01,Union Bank of India,876.18,0.24,0.476522,0.506320,-0.467139

In [ ]:
print(master_df["z_score"].describe())

count    1.080000e+02
mean    -1.631925e-17
std      9.811304e-01
min     -1.404972e+00
25%     -6.663655e-01
50%     -4.057290e-01
75%      4.155488e-01
max      3.379372e+00
Name: z_score, dtype: float64

In [ ]:
# ---------------------------------------
# Compute Monthly ISS
# ---------------------------------------

iss_monthly = (
    master_df
    .groupby("month")
    .agg(
        iss_mean_z=("z_score", "mean"),
        iss_max_z=("z_score", "max")
    )
    .reset_index()
)

# Placeholder threshold (Exploratory)
iss_monthly["stress_flag"] = iss_monthly["iss_mean_z"] > 1.5

print("Monthly ISS:")
display(iss_monthly)

Monthly ISS:

        month  iss_mean_z  iss_max_z  stress_flag
0  2024-01-01    0.165913   1.330143        False
1  2024-02-01    1.334491   2.376912        False
2  2024-03-01    0.628053   1.823902        False
3  2024-04-01    2.889914   3.379372         True
4  2024-05-01    0.397366   1.738498        False
5  2024-06-01   -0.341698   0.277416        False
6  2024-07-01   -0.260246   0.815506        False
7  2024-08-01    0.581814   0.841145        False
8  2024-09-01   -0.433303  -0.012881        False
9  2024-10-01   -0.594233  -0.543342        False
10 2024-11-01    0.289560   1.151723        False
11 2024-12-01    0.439063   2.298593        False
12 2025-01-01    0.428209   1.635769        False
13 2025-02-01   -0.459386   0.322483        False
14 2025-03-01   -0.059208   1.930034        False
15 2025-04-01   -0.141430   1.194371        False
16 2025-05-01   -0.204379   1.980964        False
17 2025-06-01   -0.306592   0.875310        False
18 2025-07-01    0.029793   0.875310        False
19 2025-08-01   -0.413472   0.540129        False
20 2025-09-01   -0.472791   0.654884        False
21 2025-10-01   -0.500404   0.213487        False
22 2025-11-01   -0.624556  -0.198155        False
23 2025-12-01    0.101110   0.911511        False
24 2026-01-01   -0.234977   0.832249        False
25 2026-04-01   -0.039631  -0.039631        False

In [ ]:
print(iss_monthly)

        month  iss_mean_z  iss_max_z  stress_flag
0  2024-01-01    0.165913   1.330143        False
1  2024-02-01    1.334491   2.376912        False
2  2024-03-01    0.628053   1.823902        False
3  2024-04-01    2.889914   3.379372         True
4  2024-05-01    0.397366   1.738498        False
5  2024-06-01   -0.341698   0.277416        False
6  2024-07-01   -0.260246   0.815506        False
7  2024-08-01    0.581814   0.841145        False
8  2024-09-01   -0.433303  -0.012881        False
9  2024-10-01   -0.594233  -0.543342        False
10 2024-11-01    0.289560   1.151723        False
11 2024-12-01    0.439063   2.298593        False
12 2025-01-01    0.428209   1.635769        False
13 2025-02-01   -0.459386   0.322483        False
14 2025-03-01   -0.059208   1.930034        False
15 2025-04-01   -0.141430   1.194371        False
16 2025-05-01   -0.204379   1.980964        False
17 2025-06-01   -0.306592   0.875310        False
18 2025-07-01    0.029793   0.875310        False
19 2025-08-01   -0.413472   0.540129        False
20 2025-09-01   -0.472791   0.654884        False
21 2025-10-01   -0.500404   0.213487        False
22 2025-11-01   -0.624556  -0.198155        False
23 2025-12-01    0.101110   0.911511        False
24 2026-01-01   -0.234977   0.832249        False
25 2026-04-01   -0.039631  -0.039631        False

In [ ]:
iss_monthly.to_csv("iss_monthly.csv", index=False)

print("ISS file saved successfully!")

ISS file saved successfully!

In [ ]:
# Find the row with the highest z-score for each month
max_bank_df = (
    master_df.loc[
        master_df.groupby("month")["z_score"].idxmax(),
        ["month", "upi_remitter_banks", "z_score"]
    ]
    .rename(columns={
        "upi_remitter_banks": "max_bank",
        "z_score": "iss_max_z_check"
    })
)

display(max_bank_df)

         month              max_bank  iss_max_z_check
2   2024-01-01   Union Bank of India         1.330143
5   2024-02-01   Union Bank of India         2.376912
8   2024-03-01   Union Bank of India         1.823902
9   2024-04-01        Bank of Baroda         3.379372
12  2024-05-01        Bank of Baroda         1.738498
16  2024-06-01  Punjab National Bank         0.277416
19  2024-07-01        Bank of Baroda         0.815506
21  2024-08-01        Bank of Baroda         0.841145
25  2024-09-01   Union Bank of India        -0.012881
26  2024-10-01        Bank of Baroda        -0.543342
30  2024-11-01        HDFC Bank Ltd.         1.151723
34  2024-12-01  Punjab National Bank         2.298593
40  2025-01-01   State Bank of India         1.635769
43  2025-02-01        HDFC Bank Ltd.         0.322483
50  2025-03-01   State Bank of India         1.930034
55  2025-04-01   State Bank of India         1.194371
58  2025-05-01        HDFC Bank Ltd.         1.980964
63  2025-06-01        HDFC Bank Ltd.         0.875310
68  2025-07-01        HDFC Bank Ltd.         0.875310
76  2025-08-01   Union Bank of India         0.540129
80  2025-09-01   State Bank of India         0.654884
85  2025-10-01   State Bank of India         0.213487
89  2025-11-01  Punjab National Bank        -0.198155
94  2025-12-01  Punjab National Bank         0.911511
101 2026-01-01  Punjab National Bank         0.832249
107 2026-04-01  Punjab National Bank        -0.039631

In [ ]:
# Merge the bank causing the maximum stress into the ISS table
iss_monthly = iss_monthly.merge(
    max_bank_df[["month", "max_bank"]],
    on="month",
    how="left"
)

display(iss_monthly)

        month  iss_mean_z  iss_max_z  stress_flag              max_bank
0  2024-01-01    0.165913   1.330143        False   Union Bank of India
1  2024-02-01    1.334491   2.376912        False   Union Bank of India
2  2024-03-01    0.628053   1.823902        False   Union Bank of India
3  2024-04-01    2.889914   3.379372         True        Bank of Baroda
4  2024-05-01    0.397366   1.738498        False        Bank of Baroda
5  2024-06-01   -0.341698   0.277416        False  Punjab National Bank
6  2024-07-01   -0.260246   0.815506        False        Bank of Baroda
7  2024-08-01    0.581814   0.841145        False        Bank of Baroda
8  2024-09-01   -0.433303  -0.012881        False   Union Bank of India
9  2024-10-01   -0.594233  -0.543342        False        Bank of Baroda
10 2024-11-01    0.289560   1.151723        False        HDFC Bank Ltd.
11 2024-12-01    0.439063   2.298593        False  Punjab National Bank
12 2025-01-01    0.428209   1.635769        False   State Bank of India
13 2025-02-01   -0.459386   0.322483        False        HDFC Bank Ltd.
14 2025-03-01   -0.059208   1.930034        False   State Bank of India
15 2025-04-01   -0.141430   1.194371        False   State Bank of India
16 2025-05-01   -0.204379   1.980964        False        HDFC Bank Ltd.
17 2025-06-01   -0.306592   0.875310        False        HDFC Bank Ltd.
18 2025-07-01    0.029793   0.875310        False        HDFC Bank Ltd.
19 2025-08-01   -0.413472   0.540129        False   Union Bank of India
20 2025-09-01   -0.472791   0.654884        False   State Bank of India
21 2025-10-01   -0.500404   0.213487        False   State Bank of India
22 2025-11-01   -0.624556  -0.198155        False  Punjab National Bank
23 2025-12-01    0.101110   0.911511        False  Punjab National Bank
24 2026-01-01   -0.234977   0.832249        False  Punjab National Bank
25 2026-04-01   -0.039631  -0.039631        False  Punjab National Bank

In [ ]:
iss_monthly["month"] = iss_monthly["month"].dt.strftime("%Y-%m")

iss_monthly.to_csv("iss_monthly.csv", index=False)

print("Updated ISS file saved successfully!")

Updated ISS file saved successfully!

In [ ]:
# Convert month to the same format as iss_monthly
max_bank_df["month"] = max_bank_df["month"].dt.strftime("%Y-%m")

# Now merge
iss_monthly = iss_monthly.merge(
    max_bank_df,
    on="month",
    how="left"
)

display(iss_monthly)

,month,iss_mean_z,iss_max_z,stress_flag,max_bank_x,max_bank_y,iss_max_z_check
0,2024-01,0.165913,1.330143,False,Union Bank of India,Union Bank of India,1.330143
1,2024-02,1.334491,2.376912,False,Union Bank of India,Union Bank of India,2.376912
2,2024-03,0.628053,1.823902,False,Union Bank of India,Union Bank of India,1.823902
3,2024-04,2.889914,3.379372,True,Bank of Baroda,Bank of Baroda,3.379372
4,2024-05,0.397366,1.738498,False,Bank of Baroda,Bank of Baroda,1.738498
5,2024-06,-0.341698,0.277416,False,Punjab National Bank,Punjab National Bank,0.277416
6,2024-07,-0.260246,0.815506,False,Bank of Baroda,Bank of Baroda,0.815506
7,2024-08,0.581814,0.841145,False,Bank of Baroda,Bank of Baroda,0.841145
8,2024-09,-0.433303,-0.012881,False,Union Bank of India,Union Bank of India,-0.012881
9,2024-10,-0.594233,-0.543342,False,Bank of Baroda,Bank of Baroda,-0.543342
10,2024-11,0.289560,1.151723,False,HDFC Bank Ltd.,HDFC Bank Ltd.,1.151723
11,2024-12,0.439063,2.298593,False,Punjab National Bank,Punjab National Bank,2.298593
12,2025-01,0.428209,1.635769,False,State Bank of India,State Bank of India,1.635769
13,2025-02,-0.459386,0.322483,False,HDFC Bank Ltd.,HDFC Bank Ltd.,0.322483
14,2025-03,-0.059208,1.930034,False,State Bank of India,State Bank of India,1.930034
15,2025-04,-0.141430,1.194371,False,State Bank of India,State Bank of India,1.194371
16,2025-05,-0.204379,1.980964,False,HDFC Bank Ltd.,HDFC Bank Ltd.,1.980964
17,2025-06,-0.306592,0.875310,False,HDFC Bank Ltd.,HDFC Bank Ltd.,0.875310
18,2025-07,0.029793,0.875310,False,HDFC Bank Ltd.,HDFC Bank Ltd.,0.875310
19,2025-08,-0.413472,0.540129,False,Union Bank of India,Union Bank of India,0.540129
20,2025-09,-0.472791,0.654884,False,State Bank of India,State Bank of India,0.654884
21,2025-10,-0.500404,0.213487,False,State Bank of India,State Bank of India,0.213487
22,2025-11,-0.624556,-0.198155,False,Punjab National Bank,Punjab National Bank,-0.198155
23,2025-12,0.101110,0.911511,False,Punjab National Bank,Punjab National Bank,0.911511
24,2026-01,-0.234977,0.832249,False,Punjab National Bank,Punjab National Bank,0.832249
25,2026-04,-0.039631,-0.039631,False,Punjab National Bank,Punjab National Bank,-0.039631

In [ ]:
import glob
import os

# Read only the original NPCI monthly files
files = sorted(
    glob.glob("/content/Ecosystem-Statistics-UPI-Top-50-member-performance-*.xlsx")
)

# Add the Jan 2026 CSV
files.append("/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv")

print("Total monthly files:", len(files))

for f in files:
    print(os.path.basename(f))

Total monthly files: 29
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv

In [ ]:
# Reset the master dataframe
master_df = pd.DataFrame()

print("master_df reset successfully!")

master_df reset successfully!

In [ ]:
import os
import re

# Convert month names to month numbers
month_map = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12"
}

def extract_month(filename):
    """
    Extracts month in YYYY-MM format from NPCI filenames.
    Works even if filename contains (1), Sheet20, etc.
    """

    name = os.path.basename(filename)

    # Find year and month name anywhere in the filename
    match = re.search(r"(20\d{2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", name)

    if match:
        year = match.group(1)
        month = month_map[match.group(2)]
        return f"{year}-{month}"

    return None

In [ ]:
for f in files:
    print(os.path.basename(f), " ---> ", extract_month(f))

Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx  --->  2024-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx  --->  2024-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx  --->  2024-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx  --->  2024-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx  --->  2024-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx  --->  2024-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx  --->  2024-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx  --->  2024-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx  --->  2024-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx  --->  2024-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx  --->  2024-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx  --->  2024-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx  --->  2025-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx  --->  2025-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx  --->  2025-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx  --->  2025-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx  --->  2025-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx  --->  2025-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx  --->  2025-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx  --->  2025-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx  --->  2025-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx  --->  2025-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx  --->  2025-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx  --->  2025-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx  --->  2025-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx  --->  2025-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx  --->  2026-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx  --->  2026-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv  --->  2026-01

In [ ]:
# Create an empty list
all_data = []

# Process every monthly file
for file in files:

    print(f"Processing: {os.path.basename(file)}")

    try:
        df = clean_upi_month(file)   # <-- Your existing function
        all_data.append(df)

    except Exception as e:
        print(f"Error in {os.path.basename(file)}")
        print(e)
        print("-"*60)

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------
Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Error in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'
------------------------------------------------------------

In [ ]:
all_data = []

for file in files:

    print(f"\nProcessing: {os.path.basename(file)}")

    try:
        df = clean_upi_month(file)

        print("Rows extracted:", len(df))

        all_data.append(df)

    except Exception as e:
        print("ERROR:")
        print(e)

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

Processing: Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
ERROR:
clean_upi_month() missing 2 required positional arguments: 'month_label' and 'target_banks'

In [ ]:
target_banks = [
    "State Bank of India",
    "HDFC Bank Ltd.",
    "Bank of Baroda",
    "Union Bank of India",
    "Punjab National Bank"
]

In [ ]:
all_data = []

for file in files:

    month_label = extract_month(file)

    print(f"Processing: {month_label}")

    try:
        df = clean_upi_month(
            file,
            month_label,
            target_banks
        )

        print("Rows:", len(df))

        all_data.append(df)

    except Exception as e:
        print("ERROR:", e)

Processing: 2024-04
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Processing: 2024-08
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Processing: 2024-12
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Processing: 2024-02
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Processing: 2024-01
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Processing: 2024-07
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Processing: 2024-06
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Processing: 2024-03
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Processing: 2024-05
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Processing: 2024-11
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Processing: 2024-10
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Processing: 2024-09
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Processing: 2025-04
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Processing: 2025-04
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Processing: 2025-08
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Processing: 2025-12
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Processing: 2025-02
Rows: 5
Processing: 2025-01
Rows: 5
Processing: 2025-07
Rows: 5
Processing: 2025-06
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Processing: 2025-03
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Processing: 2025-05
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Processing: 2025-11
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Processing: 2025-10
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Processing: 2025-09
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Processing: 2025-09
ERROR: Could not find header row in /content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Processing: 2026-04
⚠️ WARNING: expected 5 banks, got 1 for 2026-04
Unique bank names found: ['State Bank Of India' 'Hdfc Bank Ltd.' 'Bank Of Baroda'
 'Union Bank Of India' 'Punjab National Bank' 'Canara Bank'
 'Kotak Mahindra Bank' 'Axis Bank Ltd.'
 'India Post Payments Bank Limited\xa0' 'Indian Bank' 'Icici Bank Ltd.'
 'Airtel Payments Bank Limited' 'Bank Of India' 'Indian Overseas Bank'
 'Central Bank Of India' 'Uco Bank' 'Federal Bank Ltd.'
 'Fino Payments Bank Ltd.' 'Bank Of Maharashtra' 'Indusind Bank Ltd.'
 'Idbi Bank Ltd.' 'Tri O Tech Solutions Private Limited' 'Yes Bank Ltd.'
 'Karnataka Bank' 'Idfc Bank Ltd.' 'The Jammu & Kashmir Bank Limited'
 'Karur Vysya Bank' 'Jio Payments Bank Ltd' 'Bandhan Bank Limited'
 'Au Small Finance Bank' 'Baroda U.P. Bank'
 'The South Indian Bank Limited' 'Nsdl Payments Bank Limited'
 'Slice Small Finance Bank Limited(North East Small Finance Bank Limited) '
 'Punjab And Sind Bank' 'Rajasthan Marudhara Gramin Bank'
 'Tamilnad Mercantile Bank Limited' 'Ujjivan Small Finance Bank Limited'
 'Karnataka Gramin Bank' 'City Union Bank' 'Kerala Gramin Bank'
 'Telangana Grameena Bank' 'Chaitanya Godavari Grameena Bank'
 'Maharashtra Gramin Bank' 'Esaf Small Finance Bank Ltd'
 'Saraswat Co-Operative Bank' 'Dbs Bank India Limited' 'Rbl Bank Ltd.'
 'Equitas Small Finance Bank' 'One Mobikwik Systems Limited']
Rows: 1
Processing: 2026-01
Rows: 5
Processing: 2026-01
Rows: 5

In [ ]:
import pandas as pd

raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx",
    header=None,
    dtype=str
)

print(raw.shape)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

display(raw.head(15))

(52, 8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Jan'24),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr. No.,upi_remitter_banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank Of India,"3,128.97",95.62%,4.19%,0.19%,11.58,96.85%
3,2,HDFC BANK LTD,"1,040.25",96.49%,3.51%,0.00%,3.34,98.84%
4,3,Bank of Baroda,781.72,95.28%,4.68%,0.04%,2.71,98.54%
5,4,Union Bank of India,753.66,94.51%,4.34%,1.15%,7.16,46.76%
6,5,Punjab National Bank,618.95,94.78%,4.95%,0.27%,2.61,88.58%
7,6,Kotak Mahindra Bank,600.83,93.64%,5.19%,1.17%,2.08,89.49%
8,7,Canara Bank,572.16,94.18%,5.38%,0.44%,3.02,85.98%
9,8,Axis Bank Ltd.,559.49,96.11%,3.58%,0.30%,2.66,60.21%
10,9,ICICI Bank,547.55,96.59%,3.32%,0.08%,1.64,95.72%
11,10,Paytm Payments Bank,410.06,96.30%,3.70%,0.01%,0.87,98.11%
12,11,Bank of India,389.29,95.33%,4.59%,0.08%,1.48,91.49%
13,12,Indian Bank,348.89,95.15%,4.47%,0.37%,1.51,84.37%
14,13,Airtel Payments Bank,337.05,89.95%,8.98%,1.07%,1.93,69.90%

In [ ]:
import pandas as pd
import numpy as np

def clean_upi_month(file_path, month_label, target_banks):

    # ---------- Read raw file ----------
    if file_path.lower().endswith(".csv"):
        raw = pd.read_csv(file_path, header=None, dtype=str)
    else:
        raw = pd.read_excel(file_path, header=None, dtype=str)

    # ---------- Detect header row ----------
    header_row = None

    for i in range(len(raw)):
        row = raw.iloc[i].fillna("").astype(str).str.lower()

        if (
            row.str.contains("upi_remitter_banks").any()
            or row.str.contains("upi remitter banks").any()
            or row.str.contains("upi_remitter_members").any()
            or row.str.contains("upi remitter members").any()
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(f"Could not find header row in {file_path}")

    # ---------- Read again using detected header ----------
    if file_path.lower().endswith(".csv"):
        df = pd.read_csv(file_path, header=header_row)
    else:
        df = pd.read_excel(file_path, header=header_row)

    # ---------- Standardize column names ----------
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    # ---------- Bank column ----------
    if "upi_remitter_banks" in df.columns:
        bank_col = "upi_remitter_banks"
    elif "upi_remitter_members" in df.columns:
        bank_col = "upi_remitter_members"
    else:
        raise ValueError("Bank column not found.")

    # ---------- Rename columns ----------
    rename_dict = {
        bank_col: "upi_remitter_banks",
        "total_volume_(in_mn)": "total_volume_in_mn",
        "total_volume_(in_mn.)": "total_volume_in_mn",
        "td%": "td_pct",
        "td_%": "td_pct"
    }

    df = df.rename(columns=rename_dict)

    # ---------- Keep only target banks ----------
    df["upi_remitter_banks"] = (
        df["upi_remitter_banks"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    target_map = {
        "state bank of india": "State Bank of India",
        "state bank of india ": "State Bank of India",
        "state bank of india.": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "hdfc bank ltd.": "HDFC Bank Ltd.",
        "hdfc bank ltd": "HDFC Bank Ltd.",
        "bank of baroda": "Bank of Baroda",
        "union bank of india": "Union Bank of India",
        "punjab national bank": "Punjab National Bank"
    }

    df = df[df["upi_remitter_banks"].isin(target_map.keys())]

    df["upi_remitter_banks"] = df["upi_remitter_banks"].map(target_map)

    # ---------- TD cleaning ----------
    df["td_pct"] = df["td_pct"].astype(str)

    def convert_td(x):

        x = str(x).strip()

        if "%" in x:
            return float(x.replace("%", ""))

        value = float(x)

        if value <= 0.02:
            return value * 100

        return value

    df["td_pct"] = df["td_pct"].apply(convert_td)

    # ---------- Add month ----------
    df["month"] = month_label

    # ---------- Return required columns ----------
    return df[
        [
            "month",
            "upi_remitter_banks",
            "total_volume_in_mn",
            "td_pct",
        ]
    ].reset_index(drop=True)

In [ ]:
import pandas as pd

df = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx",
    header=1
)

print(df.columns.tolist())

['Sr. No.', 'upi_remitter_banks', 'Total Volume (In Mn)', 'Approved %', 'BD %', 'TD%', 'Total Debit Reversal Count (In Mn)', 'Debit Reversal Success %']

In [ ]:
import pandas as pd

# Read the file exactly the way the function does
raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx",
    header=None,
    dtype=str
)

# Find header row
header_row = None

for i in range(len(raw)):
    row = raw.iloc[i].fillna("").astype(str).str.lower()

    if (
        row.str.contains("upi_remitter_banks").any()
        or row.str.contains("upi remitter banks").any()
        or row.str.contains("upi_remitter_members").any()
        or row.str.contains("upi remitter members").any()
    ):
        header_row = i
        break

print("Header row:", header_row)

# Read again using detected header
df = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx",
    header=header_row
)

# Normalize column names
df.columns = (
    df.columns.astype(str)
      .str.strip()
      .str.lower()
      .str.replace(" ", "_", regex=False)
)

print(df.columns.tolist())

Header row: 0
["upi_remitter_members_-_top_50_members_(jan'24)", 'unnamed:_1', 'unnamed:_2', 'unnamed:_3', 'unnamed:_4', 'unnamed:_5', 'unnamed:_6', 'unnamed:_7']

In [ ]:
import pandas as pd
import numpy as np
import os

def clean_upi_month(file_path, month_label, target_banks):

    # -----------------------------
    # Read raw file
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        raw = pd.read_csv(file_path, header=None, dtype=str)
    else:
        raw = pd.read_excel(file_path, header=None, dtype=str)

    # -----------------------------
    # Find the REAL header row
    # -----------------------------
    header_row = None

    for i in range(len(raw)):

        row = raw.iloc[i].fillna("").astype(str).str.lower().tolist()

        if (
            "sr. no." in row and
            (
                "upi_remitter_banks" in row or
                "upi_remitter_members" in row
            )
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(f"Header row not found in {os.path.basename(file_path)}")

    # -----------------------------
    # Read again using detected header
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        df = pd.read_csv(file_path, header=header_row)
    else:
        df = pd.read_excel(file_path, header=header_row)

    # -----------------------------
    # Standardize column names
    # -----------------------------
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

    # -----------------------------
    # Detect bank column
    # -----------------------------
    if "upi_remitter_banks" in df.columns:
        bank_col = "upi_remitter_banks"
    elif "upi_remitter_members" in df.columns:
        bank_col = "upi_remitter_members"
    else:
        raise ValueError(f"Bank column not found in {os.path.basename(file_path)}")

    # Rename to common name
    df = df.rename(columns={bank_col: "upi_remitter_banks"})

    # -----------------------------
    # Rename remaining columns
    # -----------------------------
    rename_dict = {
        "total_volume_(in_mn)": "total_volume_in_mn",
        "td%": "td_pct"
    }

    df = df.rename(columns=rename_dict)

    # -----------------------------
    # Standardize bank names
    # -----------------------------
    df["upi_remitter_banks"] = (
        df["upi_remitter_banks"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    bank_map = {
        "state bank of india": "State Bank of India",
        "state bank of india ": "State Bank of India",
        "state bank of india.": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "state bank of india": "State Bank of India",
        "hdfc bank ltd.": "HDFC Bank Ltd.",
        "hdfc bank ltd": "HDFC Bank Ltd.",
        "bank of baroda": "Bank of Baroda",
        "union bank of india": "Union Bank of India",
        "punjab national bank": "Punjab National Bank"
    }

    df = df[df["upi_remitter_banks"].isin(bank_map.keys())]

    df["upi_remitter_banks"] = df["upi_remitter_banks"].map(bank_map)

    # -----------------------------
    # TD% cleaning
    # -----------------------------
    def convert_td(x):

        x = str(x).strip()

        if "%" in x:
            return float(x.replace("%", ""))

        value = float(x)

        if value <= 0.02:
            return value * 100

        return value

    df["td_pct"] = df["td_pct"].apply(convert_td)

    # -----------------------------
    # Add month
    # -----------------------------
    df["month"] = month_label

    # -----------------------------
    # Return cleaned dataframe
    # -----------------------------
    return df[
        [
            "month",
            "upi_remitter_banks",
            "total_volume_in_mn",
            "td_pct"
        ]
    ].reset_index(drop=True)

In [ ]:
df = clean_upi_month(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx",
    "2024-01",
    target_banks
)

display(df)

     month    upi_remitter_banks total_volume_in_mn  td_pct
0  2024-01   State Bank of India           3,128.97    0.19
1  2024-01        HDFC Bank Ltd.           1,040.25    0.00
2  2024-01        Bank of Baroda             781.72    0.04
3  2024-01   Union Bank of India             753.66    1.15
4  2024-01  Punjab National Bank             618.95    0.27

In [ ]:
all_data = []

for file in files:

    month_label = extract_month(file)

    print(f"Processing {month_label}...")

    try:
        df = clean_upi_month(
            file,
            month_label,
            target_banks
        )

        print(f"✓ {len(df)} rows")

        all_data.append(df)

    except Exception as e:

        print(f"❌ {month_label}")
        print(e)

Processing 2024-04...
✓ 5 rows
Processing 2024-08...
✓ 5 rows
Processing 2024-12...
✓ 5 rows
Processing 2024-02...
✓ 5 rows
Processing 2024-01...
✓ 5 rows
Processing 2024-07...
✓ 5 rows
Processing 2024-06...
✓ 5 rows
Processing 2024-03...
✓ 5 rows
Processing 2024-05...
✓ 5 rows
Processing 2024-11...
✓ 5 rows
Processing 2024-10...
✓ 5 rows
Processing 2024-09...
✓ 5 rows
Processing 2025-04...
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Processing 2025-04...
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Processing 2025-08...
❌ 2025-08
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Processing 2025-12...
✓ 5 rows
Processing 2025-02...
❌ 2025-02
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Processing 2025-01...
❌ 2025-01
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Processing 2025-07...
❌ 2025-07
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Processing 2025-06...
❌ 2025-06
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Processing 2025-03...
❌ 2025-03
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Processing 2025-05...
❌ 2025-05
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Processing 2025-11...
✓ 5 rows
Processing 2025-10...
✓ 5 rows
Processing 2025-09...
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Processing 2025-09...
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Processing 2026-04...
❌ 2026-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Processing 2026-01...
❌ 2026-01
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx
Processing 2026-01...
❌ 2026-01
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv

In [ ]:
import pandas as pd

raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx",
    header=None,
    dtype=str
)

print(raw.shape)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 15)

display(raw.head(15))

(52, 8)

,0,1,2,3,4,5,6,7
0,UPI Remitter Members - Top 50 Members (Jan'25),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr. No.,UPI Remitter Banks,Total Volume (In Mn),Approved %,BD %,TD%,Total Debit Reversal Count (In Mn),Debit Reversal Success %
2,1,State Bank of India,4664.49,0.9122,0.0793,0.0084,15.63,0.9706
3,2,HDFC Bank Ltd.,1419.33,0.9364,0.0628,0.0008,4.12,0.9891
4,3,Bank of Baroda,1159.99,0.9122,0.085,0.0028,3.31,0.9733
5,4,Union Bank of India,1086.26,0.9125,0.0807,0.0068,5.11,0.5675
6,5,Punjab National Bank,976.62,0.8956,0.1031,0.0013,2.99,0.9861
7,6,Kotak Mahindra Bank,889.41,0.8973,0.1022,0.0006,2.24,0.8954
8,7,Canara Bank,835.68,0.9183,0.078,0.0037,3.08,0.7991
9,8,Axis Bank Ltd.,821.68,0.9347,0.0651,0.0002,1.83,0.9514
10,9,ICICI Bank Ltd.,692.71,0.9498,0.0496,0.0006,1.36,0.9836
11,10,Bank Of India,556.22,0.9258,0.0705,0.0037,2.28,0.7253
12,11,Airtel Payments Bank Limited,553.22,0.8584,0.1372,0.0045,2.47,0.9368
13,12,Indian Bank,539.83,0.919,0.0804,0.0006,1.33,0.9395
14,13,India Post Payments Bank Ltd.,496.43,0.8369,0.148,0.0151,2.6,0.5791

In [ ]:
import pandas as pd
import numpy as np
import os

def clean_upi_month(file_path, month_label, target_banks):

    # -----------------------------
    # Read file
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        raw = pd.read_csv(file_path, header=None, dtype=str)
    else:
        raw = pd.read_excel(file_path, header=None, dtype=str)

    # -----------------------------
    # Find header row
    # -----------------------------
    header_row = None

    for i in range(len(raw)):

        row = (
            raw.iloc[i]
            .fillna("")
            .astype(str)
            .str.lower()
            .tolist()
        )

        row_text = " ".join(row)

        if (
            "sr. no." in row_text
            and (
                "upi remitter banks" in row_text
                or "upi_remitter_banks" in row_text
                or "upi remitter members" in row_text
                or "upi_remitter_members" in row_text
            )
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(
            f"Header row not found in {os.path.basename(file_path)}"
        )

    # -----------------------------
    # Read again using correct header
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        df = pd.read_csv(file_path, header=header_row)
    else:
        df = pd.read_excel(file_path, header=header_row)

    # -----------------------------
    # Standardize column names initially
    # -----------------------------
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

    # -----------------------------
    # Detect bank column and rename it
    # -----------------------------
    bank_col_name = None

    for col in df.columns:

        c = col.lower()

        if (
            "remitter" in c
            and (
                "bank" in c
                or "member" in c
            )
        ):
            bank_col_name = col
            break

    if bank_col_name is None:
        raise ValueError("Bank column not found.")

    df = df.rename(columns={bank_col_name: "upi_remitter_banks"})

    # -----------------------------
    # Find Volume and TD columns
    # -----------------------------
    volume_col = None
    td_col = None
    for col in df.columns:
        c = str(col).lower().strip()

        if volume_col is None and "total" in c and "volume" in c:
            volume_col = col

        if td_col is None and c.startswith("td"):
            td_col = col

    if volume_col is None:
        raise ValueError("Total Volume column not found.")

    if td_col is None:
        raise ValueError("TD column not found.")

    df = df.rename(columns={
        volume_col: "total_volume_in_mn",
        td_col: "td_raw"
    })

    # Remove duplicate columns
    df = df.loc[:, ~df.columns.duplicated()]

    # -----------------------------
    # Standardize bank names
    # -----------------------------
    df["upi_remitter_banks"] = (
        df["upi_remitter_banks"]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace({
            "state bank of india": "State Bank of India",
            "state bank of india ": "State Bank of India",
            "state bank of india.": "State Bank of India",
            "state bank of india ltd.": "State Bank of India",
            "hdfc bank ltd.": "HDFC Bank Ltd.",
            "hdfc bank ltd": "HDFC Bank Ltd.",
            "hdfc bank": "HDFC Bank Ltd.",
            "hdfc bank limited": "HDFC Bank Ltd.",
            "bank of baroda": "Bank of Baroda",
            "union bank of india": "Union Bank of India",
            "punjab national bank": "Punjab National Bank"
        })
    )

    # -----------------------------
    # Keep only required banks
    # -----------------------------
    df = df[df["upi_remitter_banks"].isin(target_banks)].copy()

    # -----------------------------
    # Clean Total Volume
    # -----------------------------
    df["total_volume_in_mn"] = (
        df["total_volume_in_mn"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .astype(float)
    )

    # -----------------------------
    # Convert TD values
    # -----------------------------
    def convert_td(x):

        if pd.isna(x):
            return np.nan

        x = str(x).strip()

        if "%" in x:
            return float(x.replace("%", ""))

        val = float(x)

        # 2025 decimal format
        if val <= 0.05:
            return val * 100

        return val

    df["td_pct"] = df["td_raw"].apply(convert_td)

    # -----------------------------
    # Final output
    # -----------------------------
    df["month"] = month_label

    return df[
        [
            "month",
            "upi_remitter_banks",
            "total_volume_in_mn",
            "td_pct"
        ]
    ]

In [ ]:
print(df.columns.tolist())

['month', 'upi_remitter_banks', 'total_volume_in_mn', 'td_pct']

In [ ]:
print(df.columns[df.columns.duplicated()])

Index([], dtype='object')

In [ ]:
print(df.loc[:, df.columns == "td_raw"].head())

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
print(target_banks)

df = clean_upi_month(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx",
    "2025-01",
    target_banks
)

print(df.head())

['State Bank of India', 'HDFC Bank Ltd.', 'Bank of Baroda', 'Union Bank of India', 'Punjab National Bank']
     month    upi_remitter_banks  total_volume_in_mn  td_pct
0  2025-01   State Bank of India             4664.49    0.84
1  2025-01        HDFC Bank Ltd.             1419.33    0.08
2  2025-01        Bank of Baroda             1159.99    0.28
3  2025-01   Union Bank of India             1086.26    0.68
4  2025-01  Punjab National Bank              976.62    0.13

In [ ]:
raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx",
    header=1
)

print(raw.columns.tolist())

['Sr. No.', 'UPI Remitter Banks', 'Total Volume (In Mn)', 'Approved %', 'BD %', 'TD%', 'Total Debit Reversal Count (In Mn)', 'Debit Reversal Success %']

In [ ]:
import glob
import os
import re

# Month mapping
month_map = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12"
}

file_month_map = {}

# Read all Excel and CSV files
files = glob.glob("/content/*.xlsx") + glob.glob("/content/*.csv")

for file in files:

    name = os.path.basename(file)

    match = re.search(r"(20\d{2}).*?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", name)

    if match:
        year = match.group(1)
        month = month_map[match.group(2)]
        file_month_map[file] = f"{year}-{month}"

print("Files found:", len(file_month_map))

for f, m in file_month_map.items():
    print(os.path.basename(f), " ---> ", m)

Files found: 29
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx  --->  2024-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx  --->  2025-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx  --->  2026-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx  --->  2024-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx  --->  2024-12
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx  --->  2025-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx  --->  2024-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx  --->  2024-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx  --->  2024-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx  --->  2024-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx  --->  2025-05
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx  --->  2026-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx  --->  2025-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx  --->  2025-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx  --->  2024-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx  --->  2025-06
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx  --->  2025-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx  --->  2025-04
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx  --->  2024-03
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx  --->  2025-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx  --->  2025-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx  --->  2024-08
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx  --->  2024-07
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx  --->  2025-11
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx  --->  2025-01
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx  --->  2024-02
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx  --->  2025-09
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx  --->  2025-10
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv  --->  2026-01

In [ ]:
all_data = []

for file, month in file_month_map.items():

    try:
        print(f"Processing {month}")

        temp = clean_upi_month(file, month, target_banks)

        all_data.append(temp)

        print(f"✓ {len(temp)} rows")

    except Exception as e:
        print(f"❌ {month}")
        print(e)

Processing 2024-06
✓ 5 rows
Processing 2025-12
✓ 5 rows
Processing 2026-01
✓ 5 rows
Processing 2024-04
✓ 5 rows
Processing 2024-12
✓ 5 rows
Processing 2025-08
❌ 2025-08
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Processing 2024-11
✓ 5 rows
Processing 2024-10
✓ 5 rows
Processing 2024-05
✓ 5 rows
Processing 2024-01
✓ 5 rows
Processing 2025-05
❌ 2025-05
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Processing 2026-04
✓ 5 rows
Processing 2025-02
✓ 5 rows
Processing 2025-04
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Processing 2024-09
✓ 5 rows
Processing 2025-06
✓ 5 rows
Processing 2025-03
❌ 2025-03
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Processing 2025-04
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Processing 2024-03
✓ 5 rows
Processing 2025-09
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Processing 2025-07
✓ 5 rows
Processing 2024-08
✓ 5 rows
Processing 2024-07
✓ 5 rows
Processing 2025-11
✓ 5 rows
Processing 2025-01
✓ 5 rows
Processing 2024-02
✓ 5 rows
Processing 2025-09
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Processing 2025-10
✓ 5 rows
Processing 2026-01
✓ 5 rows

In [ ]:
master_df = pd.concat(all_data, ignore_index=True)
print(master_df.shape)

(110, 4)

In [ ]:
files_to_check = [
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx",
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx",
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx",
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx",
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx"
]

for f in files_to_check:
    print("="*80)
    print(os.path.basename(f))

    raw = pd.read_excel(f, header=None, nrows=5)

    print(raw)

================================================================================
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
                                                0                    1  \
0  UPI Remitter Members - Top 50 Members (Mar'25)                  NaN
1                                           Sr_No   upi_remitter_banks
2                                               1  State Bank of India
3                                               2       HDFC Bank Ltd.
4                                               3       Bank of Baroda

                      2           3       4       5  \
0                   NaN         NaN     NaN     NaN
1  Total Volume (In Mn)  Approved %    BD %     TD%
2               4956.07      0.9201  0.0709   0.009
3               1513.14      0.9398    0.06  0.0002
4                1270.6      0.8947   0.105  0.0003

                                    6                         7
0                                 NaN                       NaN
1  Total Debit Reversal Count (In Mn)  Debit Reversal Success %
2                               20.26                     0.863
3                                4.92                    0.9721
4                                3.86                    0.9532
================================================================================
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
                                                0                    1  \
0  UPI Remitter Members - Top 50 Members (Apr'25)                  NaN
1                                            SrNo   upi_remitter_banks
2                                               1  State Bank of India
3                                               2       HDFC Bank Ltd.
4                                               3       Bank of Baroda

                      2           3       4       5  \
0                   NaN         NaN     NaN     NaN
1  Total Volume (In Mn)  Approved %    BD %     TD%
2               4850.52      0.9183  0.0742  0.0075
3                1471.2      0.9426  0.0574       0
4               1243.19      0.8974  0.1025  0.0001

                                    6                         7
0                                 NaN                       NaN
1  Total Debit Reversal Count (In Mn)  Debit Reversal Success %
2                               14.48                    0.9318
3                                5.69                    0.9545
4                                3.92                     0.937
================================================================================
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
                                                0                    1  \
0  UPI Remitter Members - Top 50 Members (May'25)                  NaN
1                                            SrNo   upi_remitter_banks
2                                               1  State Bank of India
3                                               2       HDFC Bank Ltd.
4                                               3       Bank of Baroda

                      2           3       4       5  \
0                   NaN         NaN     NaN     NaN
1  Total Volume (In Mn)  Approved %    BD %     TD%
2               4972.91      0.9387  0.0588  0.0025
3               1512.37      0.9502  0.0486  0.0012
4               1262.84      0.9127  0.0864  0.0009

                                    6                         7
0                                 NaN                       NaN
1  Total Debit Reversal Count (In Mn)  Debit Reversal Success %
2                                12.1                    0.9508
3                                2.28                    0.9993
4                                2.65                    0.9859
================================================================================
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
                                                0                    1  \
0  UPI Remitter Members - Top 50 Members (Aug'25)                  NaN
1                                            SrNo   upi_remitter_banks
2                                               1  State Bank of India
3                                               2       HDFC Bank Ltd.
4                                               3       Bank of Baroda

                      2           3      4      5  \
0                   NaN         NaN    NaN    NaN
1  Total Volume (In Mn)  Approved %   BD %    TD%
2              5,368.74      93.66%  5.92%  0.42%
3              1,581.09      95.37%  4.63%  0.01%
4              1,369.53      91.44%  8.50%  0.05%

                                    6                         7
0                                 NaN                       NaN
1  Total Debit Reversal Count (In Mn)  Debit Reversal Success %
2                               14.51                    97.89%
3                                3.51                    98.73%
4                                3.73                    99.03%
================================================================================
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
                                                0                    1  \
0  UPI Remitter Members - Top 50 Members (Sep'25)                  NaN
1                                            SrNo   upi_remitter_banks
2                                               1  State Bank of India
3                                               2       HDFC Bank Ltd.
4                                               3       Bank of Baroda

                      2           3      4      5  \
0                   NaN         NaN    NaN    NaN
1  Total Volume (In Mn)  Approved %   BD %    TD%
2              5,275.12      93.04%  6.32%  0.64%
3              1,536.13      95.06%  4.94%  0.01%
4              1,356.34      91.15%  8.73%  0.13%

                                    6                         7
0                                 NaN                       NaN
1  Total Debit Reversal Count (In Mn)  Debit Reversal Success %
2                               17.37                    91.38%
3                                3.51                    97.83%
4                                4.21                    97.01%

In [ ]:
# -----------------------------
# Find header row
# -----------------------------
header_row = None

for i in range(len(raw)):

    row_text = "".join(
        raw.iloc[i]
        .fillna("")
        .astype(str)
        .str.lower()
        .tolist()
    )

    row_text = (
        row_text
        .replace("_", "")
        .replace(".", "")
        .replace(" ", "")
    )

    if (
        ("srno" in row_text)
        and
        (
            "upiremitterbanks" in row_text
            or "upiremittermembers" in row_text
        )
    ):
        header_row = i
        break

if header_row is None:
    raise ValueError(f"Header row not found in {os.path.basename(file_path)}")

In [ ]:
# -----------------------------
# Find header row
# -----------------------------
header_row = None

for i in range(len(raw)):

    row = (
        raw.iloc[i]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
        .tolist()
    )

    # Detect the actual header row
    if (
        ("upi_remitter_banks" in row or "upi remitter banks" in row)
        and ("td%" in row or "td %" in row)
    ):
        header_row = i
        break

if header_row is None:
    raise ValueError(
        f"Header row not found in {os.path.basename(file_path)}"
    )

In [ ]:
raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx",
    header=None,
    dtype=str
)

for i in range(5):
    print("\nROW", i)
    print(raw.iloc[i].fillna("").astype(str).tolist())

ROW 0
["UPI Remitter Members - Top 50 Members (Mar'25)", '', '', '', '', '', '', '']

ROW 1
['Sr_No', 'upi_remitter_banks', 'Total Volume (In Mn)', 'Approved %', 'BD %', 'TD%', 'Total Debit Reversal Count (In Mn)', 'Debit Reversal Success %']

ROW 2
['1', 'State Bank of India', '4956.07', '0.9201', '0.0709', '0.009', '20.26', '0.863']

ROW 3
['2', 'HDFC Bank Ltd.', '1513.14', '0.9398', '0.06', '0.0002', '4.92', '0.9721']

ROW 4
['3', 'Bank of Baroda', '1270.6', '0.8947', '0.105', '0.0003', '3.86', '0.9532']

In [ ]:
raw = pd.read_excel(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx",
    header=None,
    dtype=str
)

for i in range(len(raw)):

    row = (
        raw.iloc[i]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
        .tolist()
    )

    print(i, row)

    if (
        ("upi_remitter_banks" in row or "upi remitter banks" in row)
        and ("td%" in row or "td %" in row)
    ):
        print("FOUND HEADER AT ROW:", i)
        break

0 ["upi remitter members - top 50 members (mar'25)", '', '', '', '', '', '', '']
1 ['sr_no', 'upi_remitter_banks', 'total volume (in mn)', 'approved %', 'bd %', 'td%', 'total debit reversal count (in mn)', 'debit reversal success %']
FOUND HEADER AT ROW: 1

In [ ]:
print(clean_upi_month.__code__.co_firstlineno)

5

In [ ]:
print(clean_upi_month.__code__.co_firstlineno)

5

In [ ]:
import os

files = sorted(os.listdir("/content"))

for f in files:
    if "Remitter" in f:
        print(f)

Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx

In [ ]:
import os
import re

month_map = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12"
}

file_month_map = {}

for file in os.listdir("/content"):

    if "Remitter" not in file:
        continue

    match = re.search(r"(20\d{2})-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)", file)

    if match:
        year = match.group(1)
        month = month_map[match.group(2)]
        file_month_map[file] = f"{year}-{month}"

print("Total files:", len(file_month_map))

for k, v in sorted(file_month_map.items()):
    print(v, "->", k)

Total files: 29
2024-04 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx
2024-08 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx
2024-12 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx
2024-02 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx
2024-01 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx
2024-07 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx
2024-06 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx
2024-03 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx
2024-05 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx
2024-11 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx
2024-10 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx
2024-09 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx
2025-04 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
2025-04 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
2025-08 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
2025-12 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx
2025-02 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx
2025-01 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx
2025-07 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx
2025-06 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx
2025-03 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
2025-05 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
2025-11 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx
2025-10 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx
2025-09 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
2025-09 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
2026-04 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Apr-Remitter.xlsx
2026-01 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter - Sheet20.csv
2026-01 -> Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx

In [ ]:
all_data = []

for file, month in sorted(file_month_map.items(), key=lambda x: x[1]):

    print("Processing", month)

    try:
        df = clean_upi_month(
            os.path.join("/content", file),
            month,
            target_banks
        )

        all_data.append(df)
        print("✓", len(df), "rows")

    except Exception as e:
        print("❌", month)
        print(e)

master_df = pd.concat(all_data, ignore_index=True)

print("\nMaster Shape:", master_df.shape)

master_df.head()

Processing 2024-01
✓ 5 rows
Processing 2024-02
✓ 5 rows
Processing 2024-03
✓ 5 rows
Processing 2024-04
✓ 5 rows
Processing 2024-05
✓ 5 rows
Processing 2024-06
✓ 5 rows
Processing 2024-07
✓ 5 rows
Processing 2024-08
✓ 5 rows
Processing 2024-09
✓ 5 rows
Processing 2024-10
✓ 5 rows
Processing 2024-11
✓ 5 rows
Processing 2024-12
✓ 5 rows
Processing 2025-01
✓ 5 rows
Processing 2025-02
✓ 5 rows
Processing 2025-03
❌ 2025-03
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx
Processing 2025-04
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter (1).xlsx
Processing 2025-04
❌ 2025-04
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx
Processing 2025-05
❌ 2025-05
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx
Processing 2025-06
✓ 5 rows
Processing 2025-07
✓ 5 rows
Processing 2025-08
❌ 2025-08
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx
Processing 2025-09
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx
Processing 2025-09
❌ 2025-09
Header row not found in Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter (1).xlsx
Processing 2025-10
✓ 5 rows
Processing 2025-11
✓ 5 rows
Processing 2025-12
✓ 5 rows
Processing 2026-01
✓ 5 rows
Processing 2026-01
✓ 5 rows
Processing 2026-04
✓ 5 rows

Master Shape: (110, 4)

     month    upi_remitter_banks  total_volume_in_mn  td_pct
0  2024-01   State Bank of India             3128.97    0.19
1  2024-01        HDFC Bank Ltd.             1040.25    0.00
2  2024-01        Bank of Baroda              781.72    0.04
3  2024-01   Union Bank of India              753.66    1.15
4  2024-01  Punjab National Bank              618.95    0.27

In [ ]:
import pandas as pd
import numpy as np
import os

def clean_upi_month(file_path, month_label, target_banks):

    # -----------------------------
    # Read file
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        raw = pd.read_csv(file_path, header=None, dtype=str)
    else:
        raw = pd.read_excel(file_path, header=None, dtype=str)

    # -----------------------------
    # Detect header row automatically
    # -----------------------------
    header_row = None

    for i in range(len(raw)):

        row = (
            raw.iloc[i]
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
            .tolist()
        )

        if (
            any("remitter" in x for x in row)
            and any("volume" in x for x in row)
            and any("td" in x for x in row)
        ):
            header_row = i
            break

    if header_row is None:
        raise ValueError(f"Header row not found in {os.path.basename(file_path)}")

    # -----------------------------
    # Read again using detected header
    # -----------------------------
    if file_path.lower().endswith(".csv"):
        df = pd.read_csv(file_path, header=header_row)
    else:
        df = pd.read_excel(file_path, header=header_row)

    # -----------------------------
    # Standardize column names
    # -----------------------------
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

    # Remove duplicate columns
    df = df.loc[:, ~df.columns.duplicated()]

    # -----------------------------
    # Find required columns
    # -----------------------------
    bank_col = None
    volume_col = None
    td_col = None

    for col in df.columns:

        c = str(col).lower()

        if bank_col is None and "remitter" in c:
            bank_col = col

        if volume_col is None and "volume" in c:
            volume_col = col

        if td_col is None and c.startswith("td"):
            td_col = col

    if bank_col is None:
        raise ValueError("Bank column not found.")

    if volume_col is None:
        raise ValueError("Volume column not found.")

    if td_col is None:
        raise ValueError("TD column not found.")

    df = df.rename(columns={
        bank_col: "upi_remitter_banks",
        volume_col: "total_volume_in_mn",
        td_col: "td_raw"
    })

    # -----------------------------
    # Standardize bank names
    # -----------------------------
    bank_mapping = {
        "state bank of india": "State Bank of India",
        "hdfc bank ltd.": "HDFC Bank Ltd.",
        "hdfc bank ltd": "HDFC Bank Ltd.",
        "hdfc bank limited": "HDFC Bank Ltd.",
        "hdfc bank": "HDFC Bank Ltd.",
        "bank of baroda": "Bank of Baroda",
        "union bank of india": "Union Bank of India",
        "punjab national bank": "Punjab National Bank"
    }

    df["upi_remitter_banks"] = (
        df["upi_remitter_banks"]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace(bank_mapping)
    )

    # -----------------------------
    # Keep only target banks
    # -----------------------------
    df = df[df["upi_remitter_banks"].isin(target_banks)].copy()

    # -----------------------------
    # Clean Total Volume
    # -----------------------------
    df["total_volume_in_mn"] = (
        df["total_volume_in_mn"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .astype(float)
    )

    # -----------------------------
    # Convert TD values
    # -----------------------------
    def convert_td(x):

        if pd.isna(x):
            return np.nan

        x = str(x).strip()

        if "%" in x:
            return float(x.replace("%", ""))

        x = float(x)

        if x <= 0.05:
            x *= 100

        return x

    df["td_pct"] = df["td_raw"].apply(convert_td)

    # -----------------------------
    # Final DataFrame
    # -----------------------------
    df["month"] = month_label

    return df[
        [
            "month",
            "upi_remitter_banks",
            "total_volume_in_mn",
            "td_pct"
        ]
    ]

In [ ]:
df = clean_upi_month(
    "/content/Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx",
    "2025-03",
    target_banks
)

print(df)

     month    upi_remitter_banks  total_volume_in_mn  td_pct
0  2025-03   State Bank of India             4956.07    0.90
1  2025-03        HDFC Bank Ltd.             1513.14    0.02
2  2025-03        Bank of Baroda             1270.60    0.03
3  2025-03   Union Bank of India             1173.28    0.06
4  2025-03  Punjab National Bank             1043.06    0.33

In [ ]:
all_data = []

for file, month in sorted(file_month_map.items(), key=lambda x: x[1]):

    print(f"Processing {month}")

    try:
        df = clean_upi_month(
            os.path.join("/content", file),
            month,
            target_banks
        )

        all_data.append(df)

        print(f"✓ {len(df)} rows")

    except Exception as e:

        print(f"❌ {month}")
        print(e)

# Combine all months
master_df = pd.concat(all_data, ignore_index=True)

print("\n==============================")
print("Master Data Shape:", master_df.shape)
print("==============================")

display(master_df.head())

# Save for future use
master_df.to_csv("/content/master_df.csv", index=False)

print("\nmaster_df.csv saved successfully!")

Processing 2024-01
✓ 5 rows
Processing 2024-02
✓ 5 rows
Processing 2024-03
✓ 5 rows
Processing 2024-04
✓ 5 rows
Processing 2024-05
✓ 5 rows
Processing 2024-06
✓ 5 rows
Processing 2024-07
✓ 5 rows
Processing 2024-08
✓ 5 rows
Processing 2024-09
✓ 5 rows
Processing 2024-10
✓ 5 rows
Processing 2024-11
✓ 5 rows
Processing 2024-12
✓ 5 rows
Processing 2025-01
✓ 5 rows
Processing 2025-02
✓ 5 rows
Processing 2025-03
✓ 5 rows
Processing 2025-04
✓ 5 rows
Processing 2025-04
✓ 5 rows
Processing 2025-05
✓ 5 rows
Processing 2025-06
✓ 5 rows
Processing 2025-07
✓ 5 rows
Processing 2025-08
✓ 5 rows
Processing 2025-09

In [ ]:
iss_df = pd.read_csv("/content/iss_monthly.csv")

print(iss_df.shape)
display(iss_df.head())
print(iss_df.columns.tolist())

(26, 5)

     month  iss_mean_z  iss_max_z  stress_flag             max_bank
0  2024-01    0.165913   1.330143        False  Union Bank of India
1  2024-02    1.334491   2.376912        False  Union Bank of India
2  2024-03    0.628053   1.823902        False  Union Bank of India
3  2024-04    2.889914   3.379372         True       Bank of Baroda
4  2024-05    0.397366   1.738498        False       Bank of Baroda

['month', 'iss_mean_z', 'iss_max_z', 'stress_flag', 'max_bank']

In [ ]:
# Merge master_df with ISS dataset
final_df = pd.merge(
    master_df,
    iss_df,
    on="month",
    how="left"
)

print("Shape:", final_df.shape)

display(final_df.head())

print(final_df.isnull().sum())

Shape: (125, 8)

,month,upi_remitter_banks,total_volume_in_mn,td_pct,iss_mean_z,iss_max_z,stress_flag,max_bank
0,2024-01,State Bank of India,3128.97,0.19,0.165913,1.330143,False,Union Bank of India
1,2024-01,HDFC Bank Ltd.,1040.25,0.00,0.165913,1.330143,False,Union Bank of India
2,2024-01,Bank of Baroda,781.72,0.04,0.165913,1.330143,False,Union Bank of India
3,2024-01,Union Bank of India,753.66,1.15,0.165913,1.330143,False,Union Bank of India
4,2024-01,Punjab National Bank,618.95,0.27,0.165913,1.330143,False,Union Bank of India

month                 0
upi_remitter_banks    0
total_volume_in_mn    0
td_pct                0
iss_mean_z            0
iss_max_z             0
stress_flag           0
max_bank              0
dtype: int64

In [ ]:
print("="*50)
print("FINAL DATASET INFORMATION")
print("="*50)

print("\nShape:", final_df.shape)

print("\nColumns:")
print(final_df.columns.tolist())

print("\nData Types:")
print(final_df.dtypes)

print("\nMissing Values:")
print(final_df.isnull().sum())

==================================================
FINAL DATASET INFORMATION
==================================================

Shape: (125, 8)

Columns:
['month', 'upi_remitter_banks', 'total_volume_in_mn', 'td_pct', 'iss_mean_z', 'iss_max_z', 'stress_flag', 'max_bank']

Data Types:
month                  object
upi_remitter_banks     object
total_volume_in_mn    float64
td_pct                float64
iss_mean_z            float64
iss_max_z             float64
stress_flag              bool
max_bank               object
dtype: object

Missing Values:
month                 0
upi_remitter_banks    0
total_volume_in_mn    0
td_pct                0
iss_mean_z            0
iss_max_z             0
stress_flag           0
max_bank              0
dtype: int64

In [ ]:
print("="*50)
print("SUMMARY STATISTICS")
print("="*50)

display(final_df.describe())

==================================================
SUMMARY STATISTICS
==================================================

       total_volume_in_mn      td_pct  iss_mean_z   iss_max_z
count          125.000000  125.000000  125.000000  125.000000
mean          1815.926800    0.332720    0.089544    1.089813
std           1430.379345    0.375561    0.738004    0.888264
min            618.950000    0.000000   -0.624556   -0.543342
25%            990.080000    0.080000   -0.413472    0.540129
50%           1211.410000    0.200000   -0.141430    0.875310
75%           1542.140000    0.480000    0.397366    1.738498
max           5855.790000    1.680000    2.889914    3.379372

In [ ]:
bank_td = (
    final_df.groupby("upi_remitter_banks")["td_pct"]
    .mean()
    .sort_values(ascending=False)
)

print(bank_td)

display(bank_td)

upi_remitter_banks
State Bank of India     0.5416
Union Bank of India     0.4680
Punjab National Bank    0.2940
Bank of Baroda          0.2824
HDFC Bank Ltd.          0.0776
Name: td_pct, dtype: float64

upi_remitter_banks
State Bank of India     0.5416
Union Bank of India     0.4680
Punjab National Bank    0.2940
Bank of Baroda          0.2824
HDFC Bank Ltd.          0.0776
Name: td_pct, dtype: float64

In [ ]:
bank_volume = (
    final_df.groupby("upi_remitter_banks")["total_volume_in_mn"]
    .mean()
    .sort_values(ascending=False)
)

print(bank_volume)

display(bank_volume)

upi_remitter_banks
State Bank of India     4539.5156
HDFC Bank Ltd.          1383.8928
Bank of Baroda          1146.3536
Union Bank of India     1058.9204
Punjab National Bank     950.9516
Name: total_volume_in_mn, dtype: float64

upi_remitter_banks
State Bank of India     4539.5156
HDFC Bank Ltd.          1383.8928
Bank of Baroda          1146.3536
Union Bank of India     1058.9204
Punjab National Bank     950.9516
Name: total_volume_in_mn, dtype: float64

In [ ]:
highest_td = final_df.loc[final_df["td_pct"].idxmax()]

lowest_td = final_df.loc[final_df["td_pct"].idxmin()]

print("Highest TD%")
display(highest_td)

print("\nLowest TD%")
display(lowest_td)

Highest TD%

month                             2024-02
upi_remitter_banks    Union Bank of India
total_volume_in_mn                 754.01
td_pct                               1.68
iss_mean_z                       1.334491
iss_max_z                        2.376912
stress_flag                         False
max_bank              Union Bank of India
Name: 8, dtype: object

Lowest TD%

month                             2024-01
upi_remitter_banks         HDFC Bank Ltd.
total_volume_in_mn                1040.25
td_pct                                0.0
iss_mean_z                       0.165913
iss_max_z                        1.330143
stress_flag                         False
max_bank              Union Bank of India
Name: 1, dtype: object

In [ ]:
highest_volume = final_df.loc[
    final_df["total_volume_in_mn"].idxmax()
]

lowest_volume = final_df.loc[
    final_df["total_volume_in_mn"].idxmin()
]

print("Highest Volume")
display(highest_volume)

print("\nLowest Volume")
display(lowest_volume)

Highest Volume

month                              2026-01
upi_remitter_banks     State Bank of India
total_volume_in_mn                 5855.79
td_pct                                0.32
iss_mean_z                       -0.234977
iss_max_z                         0.832249
stress_flag                          False
max_bank              Punjab National Bank
Name: 120, dtype: object

Lowest Volume

month                              2024-01
upi_remitter_banks    Punjab National Bank
total_volume_in_mn                  618.95
td_pct                                0.27
iss_mean_z                        0.165913
iss_max_z                         1.330143
stress_flag                          False
max_bank               Union Bank of India
Name: 4, dtype: object

In [ ]:
stress_months = final_df[
    final_df["stress_flag"] == True
]

display(
    stress_months[
        [
            "month",
            "iss_mean_z",
            "iss_max_z",
            "max_bank"
        ]
    ].drop_duplicates()
)

      month  iss_mean_z  iss_max_z        max_bank
15  2024-04    2.889914   3.379372  Bank of Baroda

In [ ]:
final_df.to_csv("UPI_Master_Dataset.csv", index=False)

In [ ]:
final_df.to_csv("/content/UPI_Master_Dataset.csv", index=False)

print("File saved successfully!")

File saved successfully!

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'master_df.csv', 'UPI_Master_Dataset.csv', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2026-Jan-Remitter.xlsx', 'upi_td_2026_01.csv', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jul-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Nov-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jul-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jun-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Aug-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Sep-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Jan-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Apr-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jun-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Feb-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Aug-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Dec-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-May-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Dec-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Jan-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-May-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Nov-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Mar-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Oct-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Feb-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2024-Mar-Remitter.xlsx', '.ipynb_checkpoints', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Sep-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Oct-Remitter.xlsx', 'Ecosystem-Statistics-UPI-Top-50-member-performance-2025-Apr-Remitter.xlsx', 'iss_monthly.csv', 'sample_data']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
data_path = '/content/drive/MyDrive/UPI Research'
os.listdir(data_path)

['Complied new dataset', 'Datasets']

In [ ]:
import glob
csv_files = glob.glob('/content/drive/MyDrive/UPI Research/*.csv')